import type { Menu } from "@/lib/types";

/**
 * القائمة بالعربية — الأسعار والأصناف معتمدة من تصدير نظام نقاط البيع (POS) الفعلي،
 * وهو المصدر الرسمي للأسعار. الأوصاف مكتوبة يدوياً بأسلوب العلامة.
 * الصور: أضِف حقل image لأي صنف يشير إلى ملف تحت public/menu. راجع CONTENT.md.
 * بعض الصور مشتركة بين أصناف متشابهة بصرياً (مثال: أقراص الخبز، V60 حسب الحرارة) —
 * هذا قرار مقصود وليس خطأ.
 *
 * مهم: يجب أن يتطابق كل `id` هنا مع نظيره في menu.en.ts حتى يعمل تبديل اللغة بشكل صحيح.
 * الأسعار بالريال السعودي، والسعرات بوحدة الكيلوكالوري (سعرة حرارية) حيث توفّرت.
 */
export const menuAr: Menu = [
  {
    id: "breakfast",
    name: "فطور وزّاب",
    items: [
      {
        id: "arabic-breakfast-platter",
        excludeFrom: ["branch-2"],
        name: "تشكيلة فطور عربي",
        description: "تشكيلة غنية من أطباق الفطور المحلية، مثالية للمشاركة.",
        price: { amount: 64, currency: "SAR" },
      },
      {
        id: "areekah",
        excludeFrom: ["branch-2"],
        name: "عريكة وزّاب",
        description: "عريكة فاخرة بالعسل والسمن، تُقدّم بطريقة وزّاب الخاصة والمميّزة.",
        price: { amount: 29, currency: "SAR" },
        calories: 251,
        image: "/menu/areekah.webp",
      },
      {
        id: "local-meat",
        excludeFrom: ["branch-2"],
        name: "لحم تيس طازج",
        description: "لحم تيس طازج، مطهو بعناية على الطريقة التقليدية المحلية الأصيلة.",
        price: { amount: 39, currency: "SAR" },
        calories: 230,
        image: "/menu/local-meat.webp",
      },
      {
        id: "classic-foul",
        excludeFrom: ["branch-2"],
        name: "فول وزّاب الكلاسيك",
        description:
          "فول أبيض بزيت الزيتون النقي، محضّر على طريقة وزّاب الخاصة، ويُقدّم مع القرص الطازج.",
        price: { amount: 21, currency: "SAR" },
        calories: 210,
        badges: ["vegan"],
      },
      {
        id: "mashed-fava-beans",
        excludeFrom: ["branch-2"],
        name: "فول مكشّن",
        description: "فول مهروس بنكهة غنية، يُقدّم دافئاً مع القرص الطازج.",
        price: { amount: 23, currency: "SAR" },
        badges: ["vegan"],
        image: "/menu/mashed-fava-beans.webp",
      },
    ],
  },
  {
    id: "chef-dishes",
    name: "أطباق شيف وزّاب",
    items: [
      {
        id: "creamy-chicken-cube",
        excludeFrom: ["branch-2"],
        name: "كيوب الدجاج بالكريمة",
        description: "قطع دجاج طرية مطهوة بالكريمة الغنية داخل مكعب بريوش محمّص بالزبدة.",
        price: { amount: 41, currency: "SAR" },
        image: "/menu/creamy-chicken-cube.webp",
      },
      {
        id: "eggplant-potato-fatteh",
        excludeFrom: ["branch-2"],
        name: "فتة الباذنجان والبطاطس",
        description: "طبقات من الباذنجان والبطاطا والخس والصوص الكريمي، تتوّج بقرمشة ذهبية.",
        price: { amount: 37, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/eggplant-potato-fatteh.webp",
      },
      {
        id: "butter-cheese-omelette",
        excludeFrom: ["branch-2"],
        name: "أومليت الزبدة والأجبان",
        description:
          "أومليت مخملي بالزبدة، محشو بمزيج غني من الأجبان، ويُقدّم مع سلطة ورقيات طازجة.",
        price: { amount: 29, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/butter-cheese-omelette.webp",
      },
      {
        id: "truffle-scrambled-eggs",
        excludeFrom: ["branch-2"],
        name: "سكرامبل البيض بالترافل",
        description:
          "بريوش محمّص يعلوه بيض سكرامبل كريمي بنكهة الترافل مع صوص المشروم والبارميزان.",
        price: { amount: 37, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/truffle-scrambled-eggs.webp",
      },
      {
        id: "green-shakshuka",
        excludeFrom: ["branch-2"],
        name: "شكشوكة جرين",
        description:
          "بيض بصلصة خضراء غنية بالأعشاب العطرية، يعلوها جبن الموزاريلا، وتُقدّم مع القرص.",
        price: { amount: 29, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/green-shakshuka.webp",
      },
      {
        id: "truffle-parmesan-fries",
        excludeFrom: ["branch-2"],
        name: "بطاطس بالترافل وجبنة البارميزان",
        price: { amount: 23, currency: "SAR" },
        image: "/menu/truffle-parmesan-fries.webp",
      },
      {
        id: "halloumi-hamsah",
        excludeFrom: ["branch-2"],
        name: "حمسة حلوم بالبيستو",
        description:
          "قطع حلوم مطهوة مع البيستو بخلطة وزّاب الخاصة، تُقدّم ساخنة مع قرص وزّاب الطازج.",
        price: { amount: 34, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/halloumi-hamsah.webp",
      },
      {
        id: "beet-avocado-sourdough",
        excludeFrom: ["branch-2"],
        name: "ساوردو الشمندر والأفوكادو بالأجبان",
        description:
          "خبز ساوردو بالتخمير الطبيعي، يعلوه الأفوكادو والشمندر المتبّل والأجبان المنوّعة.",
        price: { amount: 36, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/beet-avocado-sourdough.webp",
      },
      {
        id: "makdous-scramble-croissant",
        excludeFrom: ["branch-2"],
        name: "كرواسون سكرامبل البيض مع خلطة المكدوس",
        description: "كرواسون زبدي فاخر، محشو بسكرامبل البيض الكريمي وخلطتنا الخاصة بالمكدوس.",
        price: { amount: 36, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/makdous-scramble-croissant.webp",
      },
      {
        id: "tuna-danish",
        excludeFrom: ["branch-2"],
        name: "دانيش التونة الهش",
        description: "دانيش ذهبي هش، محشو بخليط تونة كريمي فاخر، ويُقدّم مع شيبس البطاطس المقرمش.",
        price: { amount: 34, currency: "SAR" },
        image: "/menu/tuna-danish.webp",
      },
    ],
  },
  {
    id: "bakery",
    name: "المخبوزات والأقراص",
    description: "يُخبز طازجاً عند الطلب يومياً من عجينتنا البلدية بالتخمير الطبيعي.",
    items: [
      {
        id: "cheese-stuffed-disc",
        name: "قرص خبز بحشوة الأجبان",
        description:
          "يُحضّر من عجينة الأجداد المحلية بالتخمير الطبيعي، ويُخبز بالفرن ويُقدّم بحشوة الأجبان.",
        price: { amount: 19, currency: "SAR" },
        calories: 567,
        badges: ["vegetarian"],
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "halloumi-pesto-pizza-disc",
        excludeFrom: ["branch-2"],
        name: "قرص بيتزا الحلوم والبيستو",
        description: "قرص مخبوز طازجاً بطريقة البيتزا، بحشوة الحلوم والبيستو.",
        price: { amount: 27, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "halloumi-pesto-flatbread",
        excludeFrom: ["branch-2"],
        name: "فلات الحلوم والبيستو",
        description: "خبز مسطّح طازج بحشوة الحلوم والبيستو.",
        price: { amount: 43, currency: "SAR" },
        badges: ["vegetarian"],
        image: "/menu/halloumi-pesto-pizza-disc.webp",
      },
      {
        id: "sambousa-disc",
        name: "قرص سنبوسة",
        description: "قرص خبز طازج بحشوة السنبوسة.",
        price: { amount: 23, currency: "SAR" },
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "smoked-cheese-disc",
        excludeFrom: ["branch-2"],
        name: "قرص خبز بالأجبان المدخنة",
        description:
          "يُحضّر من عجينة الأجداد المحلية بالتخمير الطبيعي، ويُخبز بالفرن ويُقدّم بالأجبان المدخنة والزيتون.",
        price: { amount: 22, currency: "SAR" },
        calories: 588,
        badges: ["vegetarian"],
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "egg-cheese-disc",
        excludeFrom: ["branch-2"],
        name: "قرص خبز البيض بالأجبان",
        description:
          "يُحضّر من عجينة الأجداد المحلية بالتخمير الطبيعي، ويُقدّم بالبيض المسلوق والأجبان والزيتون.",
        price: { amount: 23, currency: "SAR" },
        calories: 419,
        badges: ["vegetarian"],
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "liver-cheese-disc",
        excludeFrom: ["branch-2"],
        name: "قرص الكبدة بالجبن",
        price: { amount: 25, currency: "SAR" },
        calories: 190,
        image: "/menu/disc-bread-generic.webp",
      },
      {
        id: "tuna-olive-disc",
        excludeFrom: ["branch-2"],
        name: "قرص التونة بالزيتون",
        price: { amount: 26, currency: "SAR" },
        calories: 200,
        image: "/menu/disc-bread-generic.webp",
      },
    ],
  },
  {
    id: "snacks",
    name: "سناكس وإضافات",
    items: [
      {
        id: "fresh-orange-juice",
        name: "عصير برتقال طازج",
        price: { amount: 10, currency: "SAR" },
        badges: ["vegan"],
      },
      {
        id: "chips",
        excludeFrom: ["branch-2"],
        name: "شبس",
        price: { amount: 9, currency: "SAR" },
        image: "/menu/chips.webp",
      },
      {
        id: "popcorn",
        excludeFrom: ["branch-2"],
        name: "فشار",
        price: { amount: 9, currency: "SAR" },
        image: "/menu/popcorn.webp",
      },
      {
        id: "mixed-nuts",
        name: "مكسرات مشكلة",
        price: { amount: 12, currency: "SAR" },
        image: "/menu/mixed-nuts.webp",
      },
      {
        id: "pumpkin-seeds",
        excludeFrom: ["branch-2"],
        name: "حب قرع",
        price: { amount: 8, currency: "SAR" },
      },
      {
        id: "dates-tahini",
        name: "تمر وطحينة",
        price: { amount: 8, currency: "SAR" },
        badges: ["vegetarian"],
      },
      {
        id: "water",
        name: "ماء",
        price: { amount: 2, currency: "SAR" },
        badges: ["vegan"],
      },
      {
        id: "sparkling-water-lemon",
        name: "مياه غازية بالليمون",
        price: { amount: 6, currency: "SAR" },
        badges: ["vegan"],
      },
      {
        id: "glass-still-water",
        name: "ماء زجاج",
        price: { amount: 4, currency: "SAR" },
        badges: ["vegan"],
      },
    ],
  },
  {
    id: "sweets",
    name: "الحلا",
    items: [
      {
        id: "wzzab-baklava",
        name: "بقلاوة وزّاب",
        price: { amount: 18, currency: "SAR" },
        calories: 1000,
      },
      {
        id: "baklava-box",
        excludeFrom: ["branch-2"],
        name: "صندوق بقلاوة وزّاب",
        price: { amount: 47, currency: "SAR" },
        calories: 1400,
        image: "/menu/baklava-box.webp",
      },
      {
        id: "pistachio-baklava",
        excludeFrom: ["branch-2"],
        name: "بقلاوة بستاشيو",
        price: { amount: 18, currency: "SAR" },
      },
      {
        id: "pistachio-baklava-box",
        excludeFrom: ["branch-2"],
        name: "صندوق بقلاوة بستاشيو",
        price: { amount: 47, currency: "SAR" },
        image: "/menu/pistachio-baklava-box.webp",
      },
      {
        id: "baklava-ice-cream",
        excludeFrom: ["branch-2"],
        name: "بقلاوة بالآيسكريم",
        price: { amount: 29, currency: "SAR" },
      },
      {
        id: "truffle-pineapple",
        excludeFrom: ["branch-2"],
        name: "ترافل أناناس",
        price: { amount: 28, currency: "SAR" },
        calories: 705,
      },
      {
        id: "truffle-mango",
        name: "ترافل مانقو",
        price: { amount: 28, currency: "SAR" },
        image: "/menu/truffle-mango.webp",
      },
      {
        id: "coconut-mango",
        name: "كوكنت مانقو",
        price: { amount: 28, currency: "SAR" },
        calories: 300,
        image: "/menu/coconut-mango.webp",
      },
      {
        id: "pecan-tiramisu",
        name: "تراميسو بيكان",
        price: { amount: 28, currency: "SAR" },
        image: "/menu/pecan-tiramisu.webp",
      },
      {
        id: "chocolate-cake",
        name: "تشوكلت كيك",
        price: { amount: 29, currency: "SAR" },
        image: "/menu/chocolate-cake.webp",
      },
      {
        id: "san-sebastian-cheesecake",
        excludeFrom: ["branch-2"],
        name: "سان سيباستيان تشيزكيك",
        price: { amount: 29, currency: "SAR" },
      },
      {
        id: "date-maamoul",
        name: "معمول تمر",
        price: { amount: 5, currency: "SAR" },
        calories: 130,
      },
      {
        id: "cheese-cell",
        name: "خلية جبن",
        description: "تُحضّر يومياً طازجة بحشوة الأجبان.",
        price: { amount: 19, currency: "SAR" },
        calories: 386,
        badges: ["vegetarian"],
      },
    ],
  },
  {
    id: "hot-beverages",
    branchOrder: { "branch-2": 1 },
    name: "الشاي والقهوة السعودية",
    items: [
      {
        id: "tea-pot",
        name: "براد شاي",
        description: "حبق، وزّاب، نعناع، مخلوط.",
        price: { amount: 30, currency: "SAR" },
        calories: 30,
        image: "/menu/tea-pot.webp",
      },
      {
        id: "leaf-tea-cup",
        name: "كوب شاي ورق",
        description: "حبق، وزّاب، نعناع، مخلوط.",
        price: { amount: 6, currency: "SAR" },
        calories: 3,
      },
      {
        id: "glass-tea-cup",
        name: "كوب شاي زجاج",
        description: "حبق، وزّاب، نعناع، مخلوط.",
        price: { amount: 9, currency: "SAR" },
        calories: 3,
      },
      {
        id: "glass-cup-refill",
        name: "إعادة تعبئة كوب زجاج",
        description: "حبق، وزّاب، نعناع، مخلوط.",
        price: { amount: 6, currency: "SAR" },
        calories: 3,
      },
      {
        id: "large-mug-tea-refill",
        excludeFrom: ["branch-2"],
        name: "إعادة تعبئة مق كبير شاي",
        price: { amount: 21, currency: "SAR" },
        calories: 25,
      },
      {
        id: "medium-mug-tea-refill",
        excludeFrom: ["branch-2"],
        name: "إعادة تعبئة مق وسط شاي",
        price: { amount: 8, currency: "SAR" },
        calories: 25,
      },
      {
        id: "saudi-coffee-pot",
        name: "دلة قهوة سعودية",
        description: "تُقدّم مع التمر والطحينة.",
        price: { amount: 33, currency: "SAR" },
        calories: 20,
        image: "/menu/saudi-coffee-pot.webp",
      },
      {
        id: "saudi-coffee-cup",
        name: "كوب قهوة سعودية",
        price: { amount: 8, currency: "SAR" },
        calories: 4,
      },
      {
        id: "large-saudi-coffee-refill",
        excludeFrom: ["branch-2"],
        name: "إعادة تعبئة مق كبير قهوة سعودية",
        price: { amount: 27, currency: "SAR" },
        calories: 4,
      },
      {
        id: "medium-saudi-coffee-refill",
        excludeFrom: ["branch-2"],
        name: "إعادة تعبئة مق وسط قهوة سعودية",
        price: { amount: 12, currency: "SAR" },
        calories: 4,
      },
      {
        id: "blue-family-mug",
        excludeFrom: ["branch-2"],
        name: "مق عائلي أزرق مع تعبئة شاي",
        description: "حبق، وزّاب، نعناع، مخلوط — حافظ للحرارة والبرودة ساعات طويلة.",
        price: { amount: 69, currency: "SAR" },
        calories: 25,
      },
      {
        id: "black-family-mug",
        excludeFrom: ["branch-2"],
        name: "مق عائلي أسود مع تعبئة شاي",
        description: "حبق، وزّاب، نعناع، مخلوط — حافظ للحرارة والبرودة ساعات طويلة.",
        price: { amount: 69, currency: "SAR" },
        calories: 25,
      },
      {
        id: "medium-mug-with-tea",
        excludeFrom: ["branch-2"],
        name: "مق وسط مع تعبئة شاي",
        description: "حبق، وزّاب، نعناع، مخلوط — حافظ للحرارة والبرودة ساعات طويلة.",
        price: { amount: 65, currency: "SAR" },
        calories: 30,
      },
      {
        id: "daffi",
        name: "كرك",
        price: { amount: 9, currency: "SAR" },
      },
      {
        id: "premium-saudi-coffee-beans",
        excludeFrom: ["branch-2"],
        name: "بن سعودي فاخر",
        description: "حبوب قهوة سعودية فاخرة، معبأة لتُحضَّر في المنزل.",
        price: { amount: 55, currency: "SAR" },
      },
      {
        id: "shisha-table",
        excludeFrom: ["branch-2"],
        name: "تشغيل شبة نار لمدة ساعة ونصف",
        price: { amount: 20, currency: "SAR" },
      },
    ],
  },
  {
    id: "coffee-of-day",
    name: "قهوة اليوم",
    items: [
      {
        id: "iced-coffee-of-day",
        excludeFrom: ["main"],
        name: "قهوة اليوم بارد",
        price: { amount: 11, currency: "SAR" },
        image: "/menu/cold-v60.webp",
      },
      {
        id: "hot-coffee-of-day",
        excludeFrom: ["main"],
        name: "قهوة اليوم حار",
        price: { amount: 11, currency: "SAR" },
        image: "/menu/hot-v60.webp",
      },
    ],
  },
  {
    id: "specialty-coffee",
    name: "القهوة المختصة",
    items: [
      {
        id: "ethiopian-cold-v60",
        excludeFrom: ["branch-2"],
        name: "إثيوبي بارد V60",
        price: { amount: 18, currency: "SAR" },
        calories: 10,
        image: "/menu/cold-v60.webp",
      },
      {
        id: "ethiopian-hot-v60",
        excludeFrom: ["branch-2"],
        name: "إثيوبي حار V60",
        price: { amount: 17, currency: "SAR" },
        calories: 10,
        image: "/menu/hot-v60.webp",
      },
      {
        id: "colombian-cold-v60",
        excludeFrom: ["branch-2"],
        name: "كولومبي بارد V60",
        price: { amount: 18, currency: "SAR" },
        calories: 10,
        image: "/menu/cold-v60.webp",
      },
      {
        id: "colombian-hot-v60",
        excludeFrom: ["branch-2"],
        name: "كولومبي حار V60",
        price: { amount: 17, currency: "SAR" },
        calories: 10,
        image: "/menu/hot-v60.webp",
      },
      {
        id: "luxury-crop-cold-v60",
        excludeFrom: ["branch-2"],
        name: "محصول فاخر بارد V60",
        price: { amount: 22, currency: "SAR" },
        calories: 15,
      },
      {
        id: "luxury-crop-hot-v60",
        excludeFrom: ["branch-2"],
        name: "محصول فاخر حار V60",
        price: { amount: 22, currency: "SAR" },
        calories: 15,
      },
      {
        id: "latte",
        excludeFrom: ["branch-2"],
        name: "لاتيه",
        price: { amount: 16, currency: "SAR" },
        calories: 100,
        image: "/menu/latte.webp",
      },
      {
        id: "ice-latte",
        excludeFrom: ["branch-2"],
        name: "آيس لاتيه",
        price: { amount: 17, currency: "SAR" },
        calories: 88,
      },
      {
        id: "cappuccino",
        excludeFrom: ["branch-2"],
        name: "كابتشينو",
        price: { amount: 16, currency: "SAR" },
        calories: 90,
        image: "/menu/cappuccino.webp",
      },
      {
        id: "flat-white",
        excludeFrom: ["branch-2"],
        name: "فلات وايت",
        price: { amount: 15, currency: "SAR" },
        calories: 40,
      },
      {
        id: "cortado",
        excludeFrom: ["branch-2"],
        name: "كورتادو",
        price: { amount: 14, currency: "SAR" },
        calories: 30,
      },
      {
        id: "macchiato",
        excludeFrom: ["branch-2"],
        name: "مكياتو",
        price: { amount: 12, currency: "SAR" },
        calories: 14,
      },
      {
        id: "espresso",
        excludeFrom: ["branch-2"],
        name: "إسبريسو",
        price: { amount: 11, currency: "SAR" },
        calories: 5,
      },
      {
        id: "ice-spanish-latte",
        excludeFrom: ["branch-2"],
        name: "آيس سبانش لاتيه",
        price: { amount: 19, currency: "SAR" },
        calories: 180,
      },
      {
        id: "spanish-latte",
        excludeFrom: ["branch-2"],
        name: "سبانش لاتيه",
        price: { amount: 18, currency: "SAR" },
        calories: 170,
      },
      {
        id: "hot-americano",
        excludeFrom: ["branch-2"],
        name: "أمريكانو حار",
        price: { amount: 13, currency: "SAR" },
        calories: 20,
      },
      {
        id: "ice-americano",
        excludeFrom: ["branch-2"],
        name: "آيس أمريكانو",
        price: { amount: 14, currency: "SAR" },
      },
      {
        id: "hot-chocolate",
        excludeFrom: ["branch-2"],
        name: "هوت شوكلت",
        price: { amount: 14, currency: "SAR" },
        calories: 30,
        badges: ["vegetarian"],
      },
    ],
  },
  {
    id: "cold-drinks",
    name: "المشروبات الباردة",
    items: [
      {
        id: "mojito-code-red",
        name: "موهيتو (كود رد)",
        price: { amount: 16, currency: "SAR" },
        calories: 190,
      },
      {
        id: "mojito-7up",
        name: "موهيتو (سفن أب)",
        price: { amount: 16, currency: "SAR" },
        calories: 190,
      },
      {
        id: "cold-hibiscus",
        name: "كركديه بارد",
        price: { amount: 17, currency: "SAR" },
        calories: 20,
        badges: ["vegan"],
        image: "/menu/cold-hibiscus.webp",
      },
      {
        id: "ice-tea",
        excludeFrom: ["branch-2"],
        name: "آيس تي",
        price: { amount: 21, currency: "SAR" },
      },
      {
        id: "alfreedo",
        excludeFrom: ["branch-2"],
        name: "الفريدو",
        price: { amount: 16, currency: "SAR" },
        image: "/menu/alfreedo.webp",
      },
    ],
  },
];
